version: '3'

services:
    app:
        build: .
        entrypoint: ./.docker/entrypoint.sh
        container_name: store-api-app
        ports:
            - 3005:3005
        volumes:
            - .:/home/node/app
