version: '3'

services:
    app:
        build: .
        entrypoint: dockerize -wait tcp://db:5432 -timeout 40s ./.docker/entrypoint.sh
        container_name: invoices-api-app
        ports:
            - 3007:3007
        volumes:
            - .:/home/node/app
        depends_on:
            - db
        extra_hosts:
            - 'host.docker.internal:172.17.0.1'

    db:
        build: .docker/postgres
        container_name: invoices-api-db
        restart: always
        tty: true
        environment:
            - POSTGRES_PASSWORD=root
            - POSTGRES_DB=invoices
        volumes:
            - .pgdata:/var/lib/postgresql/data
        ports:
            - '5433:5432'
